import type { Metadata } from "next";
import { Providers } from "./providers";

import { notoSansFont } from "@/assets/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={notoSansFont.variable}>
        <main>
          {" "}
          <Providers>{children}</Providers>
        </main>
      </body>
    </html>
  );
}
